### PR TITLE
Minimal update for objection > 0.8.

### PR DESCRIPTION
**Pull request by devel-pa**

### CODE REVIEW

**Comment by parrker** [comment]
@koskimas 
Can you please check and merge this PR, if everything is okay? We are migrating to Objection 0.8, and some features of Objection-find don't work without it.

**Comment by koskimas** [comment]
@parrker @kapouer has been maintaining this library for a while now. Unfortunately I don't have time for this library anymore, nor am I be the right person to say if this change is ok. It seems to change things in a way that is not backwards compatible

**Comment by kapouer** [comment]
I was looking into it...
`propertyRef.fullColumnName` need access to builder to be able to call `relatedTableAlias(builder)`.
As they are the changes won't work.

**Comment by parrker** [comment]
@kapouer I see... And it also seems like a it will require to re-write everything in objection-find into ES6 classes, am I right?

**Comment by kapouer** [comment]
That's not mandatory. I'm fine with old style prototypes.

**Comment by kapouer** [comment]
Closed in favor of #11.

**Pull request closed without merging**
