### PR TITLE
fix: fullColumnName, use ownerModelClass tablename

### PR DESCRIPTION
**Pull request by vigzmv**
I fixed this method in my last PR, but I found an issue with my last fix.

The last PR had its tests passing because it only tested filters in self-related tables. This fix will fix it for all relations between different tables too.

### CODE REVIEW

**Comment by vigzmv** [comment]
I will try to add some more tests this weekend to handle all cases.

**Comment by vigzmv** [comment]
This PR can be merged :smile:

**Comment by kibertoad** [comment]
How urgent is the fix? I would be much more comfortable merging it after tests are there :)

**Comment by vigzmv** [comment]
@kibertoad not urgent for me, I am using my fork in my project.
But it's a breaking bug, so it's better to merge it soon, let me keep testing it in my project to be sure everything is fine. It can be merge after few days then. :smile: 


Also, I am not sure when I will be able to add more tests, but I will try.

**Comment by kibertoad** [comment]
@vigzmv OK, I'll merge and release a patch, but please let me know what are the results of the testing after you are done :)

**Comment by marcpearson** [comment]
Hi
Excuse my english, I'm french. I'll do my best to explain

The fix for fullColumName is not working like before the depracated relatedTableAlias. Searching for a field from a relation table is not working.

I have submitted a pull request many weeks ago but you change the fix in your correction for columnName function.

The fullColumnName return from your function didn't match with the real related table name in the database. 

the query contain a criteria format like : maintable__rel__relation.myfield
But the good one should be formatted as : real_related_table_name.field

My relation is defined in the model of main table with 
{
...
relation: Model.HasOneRelation,
...
}

**Pull request merged**
