### PR TITLE
Update Objection.js used for tests to latest 1.0.0 RC.

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by kibertoad** [comment]
@kapouer Yeah, I would like to. I presume I still don't have rights to publish, though? Any chance you could publish current RC release, btw?

**Comment by kibertoad** [comment]
@kapouer CI has failed due to Node 4 no longer being supported by Objection, sorry for missing that. Created a follow-up PR for that.

**Comment by kapouer** [comment]
Done !

**Comment by kapouer** [comment]
@kibertoad `npm owner add kibertoad objection-find` done too.

**Comment by kibertoad** [comment]
@kapouer Thanks and good night!

**Pull request merged**
