### PR TITLE
fix: deprecated relatedTableAlias from objection.js, upgrade objectionjs

### LINKED ISSUE #42: Issue with filters: TypeError: this.relation.relatedTableAlias
Issue with filters

Only happens on usage with **objectionjs > 1.2.2** 

```js
module.exports = function(propertyRef, value, modelClass) {
   const fullColumnName = propertyRef.fullColumnName(),
  
  ...
}
```

on calling `propertyRef.fullColumnName()`
Error `TypeError: this.relation.relatedTableAlias is not a function` is thrown.

Any recommended solutions will be appreciated.
Thanks!

---

Update:
Looks like the `relatedTableAlias` was removed in https://github.com/Vincit/objection.js/compare/1.2.2...1.2.3#diff-1b101aaae4f893ec44a231f0578d57d7

### PR DESCRIPTION
**Pull request by vigzmv**
- Fixes #42
- objectionjs upgraded to the latest

All tests passing 🎉 

---
Hello Maintainers, thanks for this amazing library, I had an [issue](https://github.com/Vincit/objection-find/issues/42) using it with the newer objectionjs so I tried to fix it. I am very new to this so any review and changes request will be highly appreciated.
Thanks!

### CODE REVIEW

**Comment by kibertoad** [comment]
Looks good, thank you!

**Comment by vigzmv** [comment]
Hello @kibertoad, do you plan to do a release soon?

**Comment by kibertoad** [comment]
On this weekend if everything goes as planned.

**Comment by kibertoad** [comment]
@vigzmv 1.6.3 is now published. Please let me know it there are any problems with it!

**Comment by vigzmv** [comment]
@kibertoad great thanks 💯 
one small note, objectionjs version should be `>= 1.2.3`
https://github.com/Vincit/objection-find/blob/56c501456c345a6977fff37140850183aac3c3e8/package.json#L67

**Comment by kibertoad** [comment]
@vigzmv Thanks for catching that one! pushed 1.6.4 with the tweak

**Pull request merged**
