### PR TITLE
Fix TS types

### LINKED ISSUE #72: How to import objection-find with typescript
1. import * as findQuery from 'objection-find
2. import findQuery from 'objection-find'

I got this error : TypeError: objection_find_1.default is not a function

The only it works:
const findQuery = require('objection-find')

Do i need to set something in my tsconfig.json

Could you write and example in the readme, thanks

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #72

### CODE REVIEW

**Comment by kibertoad** [comment]
@thisiskalnins @marcpearson Could you please try this out locally and see if it works better?

**Comment by thisiskalnins** [comment]
Tried, works for me! Thank you!

**Comment by kibertoad** [comment]
Thank you for testing! Will release new version later today.

**Comment by thisiskalnins** [comment]
Hey, @kibertoad ! I guess I responded too early! :(

`QueryBuilder` inside `.build()` is not working.

This throws an error:

`await findQuery(Model).build(req.query, Model.query()...);`

Argument of type 'QueryBuilder<Model, Model>' is not assignable to parameter of type 'FindQueryBuilder<Model, Model> & QueryBuilder<Model, Model>.'

Maybe I'm doing something wrong?

**Comment by kibertoad** [comment]
@thisiskalnins Could you create a self-contained full repro code for this?

**Comment by thisiskalnins** [comment]
So i created a simple repo with this example.
One controller in .js that works, and the other in .ts that doesn't work.

I've used this type of builder to take advantage of easy pagination with objection.

[My repo](https://github.com/thisiskalnins/objection-find-reproduction-test)

**Comment by thisiskalnins** [comment]
@kibertoad Hey, is there any progress with this?

**Comment by kibertoad** [comment]
Thanks a lot! Will give it a shot tonight.

**Comment by kibertoad** [comment]
Please check https://github.com/Vincit/objection-find/pull/74

**Pull request merged**
