### PR TITLE
Add CircleCI configuration

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by kibertoad** [comment]
@koskimas Any chance you could give me admin rights for this repo? I want to enable CircleCI integration, but currently I lack permissions for that 😅

**Comment by alexkvak** [comment]
Do you plans to auto bump version and auto publish package to npm?

**Comment by kibertoad** [comment]
@alexkvak I was planning to wait a bit to see if there is an update #56 soon, but if not, I'll cut a new version today nevertheless.

**Comment by kibertoad** [comment]
@koskimas Sorry for pinging again. I'd like to fix CI for this repo, but I can't without admin permissions.

**Comment by koskimas** [comment]
I cant find I way to add people to travis. It seems like it's for one person only :scream: Could you just create a new travis project and I'll delete the current one.

**Comment by kibertoad** [comment]
@koskimas It's done via github permissions. I need admin access to objection-find repo on github for that to work.

**Comment by koskimas** [comment]
Maybe its managed by Vincit (I don't work for them anymore)?

**Comment by koskimas** [comment]
You have admin access to objeciton-find repo. I added that when you asked for it.

**Comment by kibertoad** [comment]
Thanks! I seem to have find all permissions I need now.

**Comment by koskimas** [comment]
I didn't do anything. You already had the permissions.

**Pull request merged**
